
-- head menu 조회 쿼리
SELECT          B.MENU_NO           AS "menuNo"     , B.MENU_ORDR         AS "menuOrdr"     , B.MENU_NM           AS "menuNm"     , B.UPPER_MENU_NO     AS "upperMenuId"     , B.MENU_DC           AS "menuDc"     , B.RELATE_IMAGE_PATH AS "relateImagePath"     , B.RELATE_IMAGE_NM   AS "relateImageNm"     , B.PROGRM_FILE_NM    AS "progrmFileNm"     , (SELECT C.URL FROM COMTNPROGRMLIST C WHERE B.PROGRM_FILE_NM = C.PROGRM_FILE_NM) AS "chkURL"    
FROM COMTNMENUCREATDTLS A, COMTNMENUINFO B     
WHERE  B.Menu_NO > 0     AND    B.UPPER_MENU_NO = 0      AND    A.MENU_NO  = B.MENU_NO     
AND    A.AUTHOR_CODE = (SELECT C.AUTHOR_CODE from COMTNEMPLYRSCRTYESTBS C                                  
  WHERE  C.SCRTY_DTRMN_TRGET_ID = 'USRCNFRM_00000000000')    ORDER BY MENU_ORDR;      
--[USRCNFRM_00000000000]


select * from COMTNMENUINFO
select * from COMTNPROGRMLIST where PROGRM_STRE_PATH = '/' and PROGRM_FILE_NM like 'EgovSite%'
select * from COMTNMENUCREATDTLS
select * from COMTNEMPLYRSCRTYESTBS

select * from LETTNPROGRMLIST where PROGRM_STRE_PATH = '/' and PROGRM_FILE_NM like 'EgovSite%'
select * from LETTNMENUINFO where MENU_NO like '10%'
select * from LETTNMENUCREATDTLS where MENU_NO like '10%'

REM INSERTING into COMTNPROGRMLIST
Insert into COMTNPROGRMLIST (PROGRM_FILE_NM,PROGRM_STRE_PATH,PROGRM_KOREAN_NM,PROGRM_DC,URL) values ('EgovSiteAddress','/','찾아오시는 길','찾아오시는 길','/EgovPageLink.do?link=main/sample_menu/EgovAboutSite');
Insert into COMTNPROGRMLIST (PROGRM_FILE_NM,PROGRM_STRE_PATH,PROGRM_KOREAN_NM,PROGRM_DC,URL) values ('EgovSiteHistory','/','연혁','연혁','/EgovPageLink.do?link=main/sample_menu/EgovAboutSite');
Insert into COMTNPROGRMLIST (PROGRM_FILE_NM,PROGRM_STRE_PATH,PROGRM_KOREAN_NM,PROGRM_DC,URL) values ('EgovSiteInfo','/','사이트 소개','사이트 소개','/EgovPageLink.do?link=main/sample_menu/EgovAboutSite');
Insert into COMTNPROGRMLIST (PROGRM_FILE_NM,PROGRM_STRE_PATH,PROGRM_KOREAN_NM,PROGRM_DC,URL) values ('EgovSiteOrganization','/','조직소개','조직소개','/EgovPageLink.do?link=main/sample_menu/EgovAboutSite');

REM INSERTING into table_export
Insert into "COMTNMENUINFO" (MENU_NM,PROGRM_FILE_NM,MENU_NO,UPPER_MENU_NO,MENU_ORDR,MENU_DC,RELATE_IMAGE_PATH,RELATE_IMAGE_NM) values ('사이트소개','dir',9000000,0,1,'사이트소개','/','/');
Insert into "COMTNMENUINFO" (MENU_NM,PROGRM_FILE_NM,MENU_NO,UPPER_MENU_NO,MENU_ORDR,MENU_DC,RELATE_IMAGE_PATH,RELATE_IMAGE_NM) values ('사이트 소개','EgovSiteInfo',9010000,9000000,1,'사이트 소개','/','/');
Insert into "COMTNMENUINFO" (MENU_NM,PROGRM_FILE_NM,MENU_NO,UPPER_MENU_NO,MENU_ORDR,MENU_DC,RELATE_IMAGE_PATH,RELATE_IMAGE_NM) values ('연혁','EgovSiteHistory',9020000,9000000,2,'연혁','/','/');
Insert into "COMTNMENUINFO" (MENU_NM,PROGRM_FILE_NM,MENU_NO,UPPER_MENU_NO,MENU_ORDR,MENU_DC,RELATE_IMAGE_PATH,RELATE_IMAGE_NM) values ('조직소개','EgovSiteOrganization',9030000,9000000,3,'조직소개','/','/');
Insert into "COMTNMENUINFO" (MENU_NM,PROGRM_FILE_NM,MENU_NO,UPPER_MENU_NO,MENU_ORDR,MENU_DC,RELATE_IMAGE_PATH,RELATE_IMAGE_NM) values ('찾아오시는 길','EgovSiteAddress',9040000,9000000,4,'찾아오시는 길','/','/');


REM INSERTING into COMTNMENUCREATDTLS
Insert into COMTNMENUCREATDTLS (MENU_NO,AUTHOR_CODE,MAPNG_CREAT_ID) values (9000000,'ROLE_ADMIN',null);
Insert into COMTNMENUCREATDTLS (MENU_NO,AUTHOR_CODE,MAPNG_CREAT_ID) values (9000000,'ROLE_ANONYMOUS',null);
--Insert into COMTNMENUCREATDTLS (MENU_NO,AUTHOR_CODE,MAPNG_CREAT_ID) values (9000000,'ROLE_USER_MEMBER',null);
Insert into COMTNMENUCREATDTLS (MENU_NO,AUTHOR_CODE,MAPNG_CREAT_ID) values (9010000,'ROLE_ADMIN',null);
Insert into COMTNMENUCREATDTLS (MENU_NO,AUTHOR_CODE,MAPNG_CREAT_ID) values (9010000,'ROLE_ANONYMOUS',null);
--Insert into COMTNMENUCREATDTLS (MENU_NO,AUTHOR_CODE,MAPNG_CREAT_ID) values (9010000,'ROLE_USER_MEMBER',null);
Insert into COMTNMENUCREATDTLS (MENU_NO,AUTHOR_CODE,MAPNG_CREAT_ID) values (9020000,'ROLE_ADMIN',null);
Insert into COMTNMENUCREATDTLS (MENU_NO,AUTHOR_CODE,MAPNG_CREAT_ID) values (9020000,'ROLE_ANONYMOUS',null);
--Insert into COMTNMENUCREATDTLS (MENU_NO,AUTHOR_CODE,MAPNG_CREAT_ID) values (9020000,'ROLE_USER_MEMBER',null);
Insert into COMTNMENUCREATDTLS (MENU_NO,AUTHOR_CODE,MAPNG_CREAT_ID) values (9030000,'ROLE_ADMIN',null);
Insert into COMTNMENUCREATDTLS (MENU_NO,AUTHOR_CODE,MAPNG_CREAT_ID) values (9030000,'ROLE_ANONYMOUS',null);
--Insert into COMTNMENUCREATDTLS (MENU_NO,AUTHOR_CODE,MAPNG_CREAT_ID) values (9030000,'ROLE_USER_MEMBER',null);
Insert into COMTNMENUCREATDTLS (MENU_NO,AUTHOR_CODE,MAPNG_CREAT_ID) values (9040000,'ROLE_ADMIN',null);
Insert into COMTNMENUCREATDTLS (MENU_NO,AUTHOR_CODE,MAPNG_CREAT_ID) values (9040000,'ROLE_ANONYMOUS',null);
--Insert into COMTNMENUCREATDTLS (MENU_NO,AUTHOR_CODE,MAPNG_CREAT_ID) values (9040000,'ROLE_USER_MEMBER',null);


commit;